#!/bin/bash
set -e
set -o pipefail
set -u
#
# a simple test that checks some client status commands work
#
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

JobName=nqrustbackup_console-status-client
#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions

start_test
rm -f "$tmp/log2.out"

cat <<END_OF_DATA >$tmp/bconcmds
@$out ${NULL_DEV}
messages
@$out $tmp/log1.out
status client=nqrustbackup-fd

@$out $tmp/log2.out
messages

@$out $tmp/log3.out
disable client=nqrustbackup-fd
status client=nqrustbackup-fd
messages

@$out $tmp/log4.out
enable client=nqrustbackup-fd
status client=nqrustbackup-fd

messages
quit
END_OF_DATA

# Start the nqrustbackup daemons
# and run the nqrustbackup_console commands from ${tmp}/bconcmds
# Further nqrustbackup_console commands can be executed by "run_nqrustbackup_console".
run_nqrustbackup_console

# if log2.out has not been written, nqrustbackup_console crashed or disconnected
# after status client command
test -f "$tmp/log2.out" || exit 2
# check that nqrustbackup-fd did not report that its disabled while being enabled
# and reports being disabled while being disabled
expect_not_grep "Client \"nqrustbackup-fd\" is disabled" \
  "$tmp/log1.out" \
  "Error found disabled confirmation while client should be enabled."
expect_not_grep "Client \"nqrustbackup-fd\" is disabled" \
  "$tmp/log2.out" \
  "Error found disabled confirmation while client should be enabled."
expect_grep "Client \"nqrustbackup-fd\" is disabled" \
  "$tmp/log3.out" \
  "Error missing disabled confirmation."
expect_not_grep "Client \"nqrustbackup-fd\" is disabled" \
  "$tmp/log4.out" \
  "Error found disabled confirmation while client should be enabled."

end_test
