#!/bin/bash
set -e
set -o pipefail
set -u
#trap read debug

#shellcheck source=../../environment.in
. ./environment
#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions
. ./reload_test_functions

TestName="$(get_test_name "$0")"
export TestName
export estat

export temporary_job_config_file="$config_directory_dir_additional_test_config/new_empty_job_definition.conf"
export nqrustbackup_console_command_file="$tmp/nqrustbackup_console_reload_command"
export console_logfile="$tmp/console.log"

############################################
start_test
############################################

remove_console_logfile

setup_config
#reload modified config
add_empty_job_to_config
test_reload_will_not_crash_director
find_error_string_in_console_log 'Config error: Name not specified for resource'

############################################
end_test
############################################
