#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-nqrustbackup-fd

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions

"${NQRUSTBACKUP_SCRIPTS_DIR}"/cleanup

start_test

${NQRUSTBACKUP_STORAGEDAEMON_BINARY} -t -c "bad.conf" >"${tmp}/out.txt" || :

expect_grep "CONFIG ERROR" \
  "${tmp}/out.txt" \
  "Config error not found"

expect_grep "get_char: called after EOF." \
  "${tmp}/out.txt" \
  "Wrong error caught"

end_test
