#!/bin/bash

#   NQRUSTBACKUP® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2025 NQRustBackup GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions
"${NQRUSTBACKUP_SCRIPTS_DIR}"/cleanup
"${NQRUSTBACKUP_SCRIPTS_DIR}"/setup

bin/nqrustbackup start
bin/nqrustbackup status

# Fill ${BackupDirectory} with data.
mkdir -p "${BackupDirectory}"
for size in 4 16 32 128; do
  generate_testdata "${BackupDirectory}/${size}k" --size=${size}k
done

# make sure that the director is up and running.
print_debug "$(bin/nqrustbackup_console <<<"status dir")"
