#!/bin/bash
#   NQRUSTBACKUP® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2019-2025 NQRustBackup GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u
# run a backup
# copy it
# purge/delete original volume
# nqrustbackup_scan
# restore

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-nqrustbackup-fd
#shellcheck source=../../environment.in
. ./environment

JobName=backup-nqrustbackup-fd
#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions
"${NQRUSTBACKUP_SCRIPTS_DIR}"/cleanup
"${NQRUSTBACKUP_SCRIPTS_DIR}"/setup
mkdir -p "${archivedir}-remote"
find "${archivedir}-remote" -mindepth 1 -delete

# Fill ${BackupDirectory} with data.
setup_data

start_test

bin/nqrustbackup start

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${NULL_DEV}
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full
run job=$JobName yes
status director
status client
status storage=File
wait
update volume=TestVolume001 volstatus=Used
messages
@#
@# do a copy
@#
@$out $tmp/log1.out
label volume=TestCopyVolume001 storage=RemoteFile pool=FullCopy
run copy yes
status director
status client
status storage=File
wait
messages
purge volume=TestVolume001 yes
delete volume=TestVolume001 yes
purge volume=TestCopyVolume001 yes
delete volume=TestCopyVolume001 yes
quit
END_OF_DATA

run_nqrustbackup_console "$tmp/bconcmds"

oldconf="${NQRUSTBACKUP_CONFIG_DIR}"
NQRUSTBACKUP_CONFIG_DIR="${NQRUSTBACKUP_CONFIG_DIR}-remote"
run_nqrustbackup_scan_db -vv -d100 -s -V TestCopyVolume001 RemoteFileStorage
ret=$?
NQRUSTBACKUP_CONFIG_DIR="${oldconf}"

if [ $ret -ne 0 ]; then
  echo "nqrustbackup_scan exit code: $ret"
  bin/nqrustbackup stop
  exit $ret
fi

# we set this to the *wrong* number that is currently written to the SOS
original_job_id=4
new_job_id=5

if ! grep -q "Created new JobId=${new_job_id} record for original JobId=${original_job_id}" "$tmp/nqrustbackup_scan.out"; then
  echo 'Job numbers of scanned job are not correct'
  bin/nqrustbackup stop
  exit 1
fi

num_sos=$(grep -c '^Begin Job Session Record:' "$tmp/nqrustbackup_scan.out")
if [ "$num_sos" -ne 1 ]; then
  echo "Found $num_sos start of session records instead of 1"
  bin/nqrustbackup stop
  exit 1
fi
num_eos=$(grep -c '^End Job Session Record:' "$tmp/nqrustbackup_scan.out")
if [ "$num_eos" -ne 1 ]; then
  echo "Found $num_eos end of session records instead of 1"
  bin/nqrustbackup stop
  exit 1
fi

total_jobid_records=$(grep -cE '^JobId +: ' "$tmp/nqrustbackup_scan.out")
my_jobid_records=$(grep -cE "^JobId +: ${original_job_id}" "$tmp/nqrustbackup_scan.out")

if [ "$my_jobid_records" -ne 2 ]; then
  echo "Got $my_jobid_records mentions of my jobid, expected 2"
  bin/nqrustbackup stop
  exit 1
fi
if [ "$my_jobid_records" -ne "$total_jobid_records" ]; then
  echo "Volume contains excess session records:"
  echo "Got $total_jobid_records in total, only $my_jobid_records mention my original jobid"
  bin/nqrustbackup stop
  exit 1
fi

cat <<END_OF_DATA >"$tmp/bconcmds2"
@#
@# now do a restore
@#
@$out $tmp/log2.out
wait
restore client=nqrustbackup-fd fileset=SelfTest where=$tmp/nqrustbackup-restores select all done
yes
wait
messages
quit
END_OF_DATA

run_nqrustbackup_console "$tmp/bconcmds2"

check_for_zombie_jobs storage=File

bin/nqrustbackup stop

check_two_logs
check_restore_diff "${BackupDirectory}"
end_test
