.. code-block:: nqrustbackuplog
    :caption: nqrustbackup.log

    08-Sep 12:58 win-fd JobId 10: secure_erase: executing C:/cygwin64/bin/shred.exe "C:/temp/nqrustbackup-restores/C/Program Files/NQRustBackup/Plugins/nqrustbackup_fd_consts.py"
    08-Sep 12:58 win-fd JobId 10: secure_erase: executing C:/cygwin64/bin/shred.exe "C:/temp/nqrustbackup-restores/C/Program Files/NQRustBackup/Plugins/nqrustbackup_sd_consts.py"
    08-Sep 12:58 win-fd JobId 10: secure_erase: executing C:/cygwin64/bin/shred.exe "C:/temp/nqrustbackup-restores/C/Program Files/NQRustBackup/Plugins/bpipe-fd.dll"
