#!/bin/bash
set -u

#shellcheck source=../environment.in
. ./environment

"bin/nqrustbackup" status
"bin/nqrustbackup" stop
"bin/nqrustbackup" status

function deletefiles()
{
  rm -rf "${tmp:?}"/*
  rm -rf "${logdir:?}"/*.log
  rm -rf "${working:?}"/*.bsr "${working:?}"/log*.sd
  rm -rf "${working:?}"/*.trace "${working:?}"/*.traceback "${working:?}"/*.bactrace
  rm -rf "${working:?}"/*.state
  rm -rf "${working:?}"/*.conmsg
  rm -rf "${working:?}"/*.cryptoc || :
  rm -rf "${working:?}"/*.pid
  rm -rf "${working:?}"/*.mail
  rm -rf "${working:?}"/CLEANUPMARKER
  rm -rf "${working:?}"/plugins/*
  rm -rf "${archivedir:?}"/*
  rm -f "${config_directory_dir_additional_test_config}"/*
  find . -name "gigaslam.gif" -exec rm -f {} \;
  # cleanup chrome user data (selenium tests)
  rm -rf /tmp/chrome-user-data-*
}

tail -n +1 "${working:?}"/*.traceback 2>/dev/null || true

deletefiles

${NQRUSTBACKUP_SCRIPTS_DIR}/drop_nqrustbackup_database ${DBTYPE} >/dev/null 2>&1

exit 0
