#!/bin/bash
set -e
set -o pipefail
set -u
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

JobName=backup-nqrustbackup-fd
#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions
"${NQRUSTBACKUP_SCRIPTS_DIR}"/cleanup
"${NQRUSTBACKUP_SCRIPTS_DIR}"/setup

# Fill ${BackupDirectory} with data.
setup_data

start_test

start_nqrustbackup

cat <<END_OF_DATA >$tmp/bconcmds
@$out ${NULL_DEV}
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full
label volume=TestVolume002 storage=File pool=Full
run job=$JobName yes
status director
status client
status storage=File
wait
messages
purge volume=TestVolume001 yes
delete volume=TestVolume001 yes
quit
END_OF_DATA

run_nqrustbackup_console "$tmp/bconcmds"

expect_device_listing()
{
  log_no_device="${tmp}/no-device-$1.out"
  "$2" -c "${NQRUSTBACKUP_CONFIG_DIR}" &>"$log_no_device" || :
  if ! grep -q "\"FileStorage\"" "$log_no_device" || ! grep -q "\"FileStorage2\"" "$log_no_device"; then
    echo "Expected listing of available devices if no device is specified but not found in output, instead got:"
    cat $log_no_device
    stop_nqrustbackup
    exit 1
  fi

  log_invalid_device="${tmp}/invalid-device-$1.out"
  "$2" -c "${NQRUSTBACKUP_CONFIG_DIR}" InvalidDevice "${@:3}" &>"$log_invalid_device" || :
  if ! grep -q "\"FileStorage\"" "$log_invalid_device" || ! grep -q "\"FileStorage2\"" "$log_invalid_device"; then
    echo "Expected listing of available devices if invalid device is specified but not found in output, instead got:"
    cat $log_invalid_device
    stop_nqrustbackup
    exit 1
  fi
}

expect_device_listing nqrustbackup_scan $NQRUSTBACKUP_NQRUSTBACKUP_SCAN_BINARY
expect_device_listing nqrustbackup_extract $NQRUSTBACKUP_NQRUSTBACKUP_EXTRACT_BINARY .
expect_device_listing bls $NQRUSTBACKUP_BLS_BINARY
expect_device_listing nqrustbackup_copy $NQRUSTBACKUP_NQRUSTBACKUP_COPY_BINARY OtherInvalidDevice
expect_device_listing nqrustbackup_tape $NQRUSTBACKUP_NQRUSTBACKUP_TAPE_BINARY

run_bls -vv -V TestVolume001 FileStorage
ret=$?
if [ $ret -ne 0 ]; then
  echo "bls exit code: $ret"
  stop_nqrustbackup
  exit $ret
fi

if ! grep -q "tests.bregtest.c" "$tmp/bls.out"; then
  echo 'Expected string \"tests.bregtest.c\" not found in  bls output'
  stop_nqrustbackup
  exit 1
fi

rm -rf "$tmp/nqrustbackup-restores"
mkdir -p "$tmp/nqrustbackup-restores"
run_nqrustbackup_extract -vv -V TestVolume001 FileStorage "$tmp/nqrustbackup-restores"
ret=$?
if [ $ret -ne 0 ]; then
  echo "nqrustbackup_extract exit code: $ret"
  stop_nqrustbackup
  exit $ret
else
  find "$tmp/nqrustbackup-restores"
  check_restore_diff "${BackupDirectory}"            # check extracted files
  mv "$tmp/nqrustbackup-restores" "$tmp/nqrustbackup_extract-restores" # move extracted files away
  mkdir -p "$tmp/nqrustbackup-restores"
fi

run_nqrustbackup_scan_db -vv -s -V TestVolume001 FileStorage
ret=$?
if [ $ret -ne 0 ]; then
  echo "nqrustbackup_scan exit code: $ret"
  stop_nqrustbackup
  exit $ret
fi

original_job_id=1
new_job_id=2

if ! grep -q "Created new JobId=${new_job_id} record for original JobId=${original_job_id}" "$tmp/nqrustbackup_scan.out"; then
  echo 'Job numbers of scanned job are not correct'
  stop_nqrustbackup
  exit 1
fi

num_sos=$(grep -c '^Begin Job Session Record:' "$tmp/nqrustbackup_scan.out")
if [ "$num_sos" -ne 1 ]; then
  echo "Found $num_sos start of session records instead of 1"
  stop_nqrustbackup
  exit 1
fi
num_eos=$(grep -c '^End Job Session Record:' "$tmp/nqrustbackup_scan.out")
if [ "$num_eos" -ne 1 ]; then
  echo "Found $num_eos end of session records instead of 1"
  stop_nqrustbackup
  exit 1
fi

total_jobid_records=$(grep -cE '^JobId +: ' "$tmp/nqrustbackup_scan.out")
my_jobid_records=$(grep -cE "^JobId +: ${original_job_id}" "$tmp/nqrustbackup_scan.out")

if [ "$my_jobid_records" -ne 2 ]; then
  echo "Got $my_jobid_records mentions of my jobid, expected 2"
  stop_nqrustbackup
  exit 1
fi
if [ "$my_jobid_records" -ne "$total_jobid_records" ]; then
  echo "Volume contains excess session records:"
  echo "Got $total_jobid_records in total, only $my_jobid_records mention my original jobid"
  stop_nqrustbackup
  exit 1
fi

# use nqrustbackup_copy to copy the job and extract it afterwards to verify copy is verbatim
# TestVolume 002 is the target volume for the copy operation
run_nqrustbackup_copy -v -i TestVolume001 -o TestVolume002 FileStorage FileStorage2

rm -rf "$tmp/nqrustbackup-restores"
mkdir -p "$tmp/nqrustbackup-restores"
run_nqrustbackup_extract -vv -V TestVolume002 FileStorage2 "$tmp/nqrustbackup-restores"
ret=$?

if [ $ret -ne 0 ]; then
  echo "nqrustbackup_extract exit code: $ret"
  stop_nqrustbackup
  exit $ret
else
  find "$tmp/nqrustbackup-restores"
  check_restore_diff "${BackupDirectory}"            # check extracted files
  mv "$tmp/nqrustbackup-restores" "$tmp/nqrustbackup_extract-restores" # move extracted files away
  mkdir -p "$tmp/nqrustbackup-restores"
fi

cat <<END_OF_DATA >"$tmp/bconcmds2"
@#
@# now do a restore
@#
@$out $tmp/log2.out
wait
restore client=nqrustbackup-fd fileset=SelfTest where=$tmp/nqrustbackup-restores select all done
yes
wait
messages
quit
END_OF_DATA

run_nqrustbackup_console "$tmp/bconcmds2"

check_for_zombie_jobs storage=File

check_two_logs
check_restore_diff "${BackupDirectory}"
end_test
