#!/bin/bash

#   NQRUSTBACKUP® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2023-2025 NQRustBackup GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

# This systemtest tests the plugin functionality
# of the NQRustBackup FD plugin nqrustbackup-fd-libcloud.py
#
# This test will start a s3minio server and populate it with some data.
# Then it runs a backup and a restore with the plugin.
# A full comparison is made afterwards.
# File attributes like uses and times will not be saved.

TestName="$(basename "$(pwd)")"
export TestName
bucket_name=nqrustbackup-test

JobName=backup-nqrustbackup-fd
#shellcheck source=../../environment.in
. ./environment
#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions

# shortcut for s3cmd
S3="${S3CMD} --no-check-certificate --config ${S3CFG}"

start_test

cat <<END_OF_DATA >${tmp}/bconcmds
@$out ${NULL_DEV}
messages
@$out ${tmp}/log1.out
setdebug level=100 trace=1 timestamp=1 storage=File
setdebug level=200 trace=1 timestamp=1 client=nqrustbackup-fd
run job=${JobName} yes
wait
setdebug level=0 client=nqrustbackup-fd
status director
status client
status storage=File
messages
END_OF_DATA

echo "Full backup stage"
run_nqrustbackup_console
expect_grep "Backup OK" "${tmp}/log1.out" "Full Backup not found!"
if [ ${estat} -ne 0 ]; then
  exit ${estat}
fi

# for incremental, add a file and delete a file
echo "incrementaldata" >${tmp}/data/testfile-inc.txt
${S3} put ${tmp}/data/testfile-inc.txt s3://${bucket_name}/data/testfile-inc.txt
${S3} rm s3://${bucket_name}/data/object-size-downloads-to-temporary-file
rm -f ${tmp}/data/object-size-downloads-to-temporary-file

cat <<END_OF_DATA >${tmp}/bconcmds
@$out ${NULL_DEV}
messages
@$out ${tmp}/log2.out
setdebug level=100 trace=1 timestamp=1 storage=File
setdebug level=200 trace=1 timestamp=1 client=nqrustbackup-fd
run job=${JobName} yes
wait
setdebug level=0 client=nqrustbackup-fd
status director
status client
status storage=File
messages
END_OF_DATA

echo "Incremental backup stage"
run_nqrustbackup_console
expect_grep "Backup OK" "${tmp}/log2.out" "Full Backup not found!"
if [ ${estat} -ne 0 ]; then
  exit ${estat}
fi

cat <<END_OF_DATA >${tmp}/bconcmds
@$out ${tmp}/log2.out
setdebug level=200 trace=1 timestamp=1 client=nqrustbackup-fd
restore client=nqrustbackup-fd fileset=PluginTest where=${tmp}/nqrustbackup-restores select all done yes
wait
messages
quit
END_OF_DATA
echo "Restore backup stage"
run_nqrustbackup_console
expect_grep "Restore OK" "${tmp}/log2.out" "Full Restore not ok!"
if [ ${estat} -ne 0 ]; then
  exit ${estat}
fi

check_for_zombie_jobs storage=File

check_two_logs

if ! diff -r tmp/data tmp/nqrustbackup-restores/${bucket_name}/data; then
  export estat=1
fi

end_test
