#!/bin/bash
set -e
set -o pipefail
set -u

# run nqrustbackup_scan and make sure it does not crash

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions
start_test

JobName=backup-nqrustbackup-fd

run_nqrustbackup_scan_db -vv -s -V TestVolume001 FileStorage
ret=$?
if [ $ret -ne 0 ]; then
  echo "nqrustbackup_scan exit code: $ret"
  stop_nqrustbackup
  exit $ret
fi

end_test
