#!/bin/bash
set -e
set -o pipefail
set -u
set -x

# run bls and make sure it works (with autoxflate plugin)
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${NQRUSTBACKUP_SCRIPTS_DIR}"/functions
start_test

JobName=backup-nqrustbackup-fd

run_nqrustbackup_copy -v -i TestVolume001 -o TestVolume002 FileStorage FileStorage2
ret=$?
if [ $ret -ne 0 ]; then
  echo "nqrustbackup_copy exit code: $ret"
  stop_nqrustbackup
  exit $ret
fi

if ! grep -q "nqrustbackup_copy: stored.nqrustbackup_copy.cc:.* . Jobs copied. .*records copied." "$tmp/nqrustbackup_copy.out"; then
  echo 'Expected string nqrustbackup_copy: stored.nqrustbackup_copy.cc:.* . Jobs copied. .*records copied" not found in nqrustbackup_copy output'
  stop_nqrustbackup
  exit 1
fi

end_test
