<?php

/**
 *
 * nqrustbackup-webui - NQRust Backup Web Console
 *
 * @link      https://github.com/nqrustbackup/nqrustbackup for the canonical source repository
 * @copyright Copyright (C) 2013-2023 NQRustBackup GmbH & Co. KG (http://www.nqrustbackup.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

echo $this->doctype();

?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('NQRust Backup', 'PREPEND')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?php echo $this->headLink(array('rel' => 'icon', 'type' => 'image/svg+xml', 'href' => $this->basePath() . '/themes/nqrust/img/favicon.svg'))
        ->prependStylesheet($this->basePath() . '/css/main.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/themes/nqrust/css/app.css');
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/excanvas.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',));
    ?>

</head>

<body>

    <div class="container">
        <?php echo $this->content; ?>
    </div>

    <?php echo $this->inlineScript() ?>

</body>

</html>
